### ISSUE TITLE
Try To Make the kernel Like Agni Kernel... For Mi Note 6 pro...

### ISSUE THREAD

**Issue by SahilNathwani** [stormbreaker-project/kernel_RMX1851#1]

**Comment by SahilNathwani** [comment]
Try to make it as AGNI kernel of Mi Note 6 pro...
The AGNI kernel guarantees constant 50 and above fps while gaming...
Also in Intense matches like competitive scrims of pUBGM..
It give 50* Fps and above constant...
Whereas our rmx1851 drops to 40fps in such cases

**Comment by danascape** [comment]
Note 6 pro and realme 3 pro are different different devices.
